# Generated by Django 4.2.30 on 2026-07-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#4A6741', max_length=9)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('lead_email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'short'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('module', 'Module'), ('fireside', 'Fireside'), ('assessment', 'Assessment'), ('activity', 'Activity')], default='module', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255)),
                ('fkind', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('date', models.DateField()),
                ('start', models.CharField(help_text='HH:MM (24h)', max_length=5)),
                ('end', models.CharField(blank=True, help_text='HH:MM (24h)', max_length=5)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed')], default='proposed', max_length=10)),
                ('mode', models.CharField(choices=[('virtual', 'Virtual'), ('inperson', 'In person')], default='virtual', max_length=10)),
                ('loc', models.CharField(blank=True, help_text='Venue or meeting link', max_length=500)),
                ('note', models.TextField(blank=True)),
                ('gcal_id', models.CharField(blank=True, help_text='Google Calendar event id (set on sync)', max_length=255)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='calendar_app.pod')),
            ],
            options={
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendar_app.pod')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('pod', 'email')},
            },
        ),
    ]
